(function() {var implementors = {};
implementors['etcd'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='etcd/keys/struct.KeySpaceInfo.html' title='etcd::keys::KeySpaceInfo'>KeySpaceInfo</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='etcd/keys/struct.Node.html' title='etcd::keys::Node'>Node</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='etcd/stats/struct.LeaderStats.html' title='etcd::stats::LeaderStats'>LeaderStats</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='etcd/stats/struct.FollowerStats.html' title='etcd::stats::FollowerStats'>FollowerStats</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='etcd/stats/struct.CountStats.html' title='etcd::stats::CountStats'>CountStats</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='etcd/stats/struct.LatencyStats.html' title='etcd::stats::LatencyStats'>LatencyStats</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='etcd/stats/struct.SelfStats.html' title='etcd::stats::SelfStats'>SelfStats</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='etcd/stats/struct.LeaderInfo.html' title='etcd::stats::LeaderInfo'>LeaderInfo</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='etcd/stats/struct.StoreStats.html' title='etcd::stats::StoreStats'>StoreStats</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
